apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: golang-demo
  description: A golang web app demoing the secure supply chain
  tags:
    - golang
    - web
  links:
    - url: https://golang-demo.default.tap.viktoriouslab.nl/
      title: App Link
      icon: dashboard
    - url: https://go.dev
      title: GoLang
      icon: dashboard
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=golang-demo
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: denmark-team
  system: cncf
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: cncf
  description: CNCF Demo
spec:
  owner: denmark-team
  domain: tap-gui-domain
